version: "3.9"

services:
  database_summoner:
    image: postgres
    container_name: database_summoner
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=summoner
      - POSTGRES_DB=summonerdb
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    links:
      - database_summoner
    depends_on:
      - database_summoner
    container_name: summonerapi
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
