#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $TYPEORM_USERNAME WITH PASSWORD '$TYPEORM_PASSWORD';
  CREATE DATABASE $TYPEORM_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $TYPEORM_DATABASE TO $TYPEORM_USERNAME;
EOSQL